const express = require('express')
const mongoose = require('mongoose')
const navRoutes = require('./routes')
const config = require('./config')
const morgan = require('morgan')
const app = express()

mongoose.connect(config.mongodbUrl, { useNewUrlParser: true })
app.set('view engine', 'ejs')
app.use(morgan('tiny'))
app.use(express.static(config.musicStorageDir))
app.use(express.static('public'))
app.use(navRoutes)

app.listen(config.port, () => console.log(`gleeMusic server running on port ${config.port}`))
