const express = require('express')
const navRoutes = require('./routes')
const config = require('./config')
const morgan = require('morgan')
const app = express()

app.set('view engine', 'ejs')
app.use(morgan('tiny'))
app.use(express.static(config.musicStorageDir))
app.use(express.static('public'))
app.use(navRoutes)
app.listen(config.port, () => console.log(`gleeMusic server running on port ${config.port}`))
